version: "3.9"

services:
  react-app:
    build: .
    environment:
      - VITE_API_URL=http://localhost:3000
      - VITE_API_VERSION=v1
      - VITE_API_KEY=D4hqIiIPrrB14KfqBVdn
    ports:
      - 5173:5173
    volumes:
      - ./:/client
      - /client/node_modules
    stdin_open: true
    tty: true
